[project]
name = "pygrlogging"
authors = [
    {name = "ruizgabriel161",email = "ruizgabriel161@outlook.com"}
]
version = "0.1.0"
description = "Biblioteca para configurar Logs" 
# ============================
# Build e Setuptools
# ============================

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ['./src/pygrlogging']

[tool.ruff]
extend = '../../pyproject.toml'

[tool.pyright]
extends = '../../pyproject.toml'